name: umaxica-apps-edge-apex

services:
  apex:
    build:
      context: .
      args:
        - DOCKER_UID=${UID:-1000}
        - DOCKER_GID=${GID:-1000}
        - DOCKER_USER=apex
        - DOCKER_GROUP=group
    working_dir: /home/apex/workspace
    volumes:
      - type: bind
        source: .
        target: /home/apex/workspace
        consistency: cached
      - type: volume
        source: node-volume
        target: /home/apex/workspace/node_modules
        volume:
          nocopy: true
    ports:
      - '5101:5101' # com
      - '5201:5201' # net
      - '5301:5301' # org
      - '5401:5401' # app
    command: sleep infinity
    tty: true
    stdin_open: true
    init: true
    environment:
      - CLOUDFLARE_ENV=development
      - VITE_GIT_HOOKS=0
      - NODE_OPTIONS=--max-old-space-size=4096
    restart: unless-stopped
volumes:
  node-volume:
    driver: local
